// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// idelta_cpp
arma::vec idelta_cpp(const arma::sp_mat& G);
RcppExport SEXP _FG2CLI_idelta_cpp(SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(idelta_cpp(G));
    return rcpp_result_gen;
END_RCPP
}
// leeL_cpp
arma::mat leeL_cpp(const arma::mat& Xz, const arma::sp_mat& W);
RcppExport SEXP _FG2CLI_leeL_cpp(SEXP XzSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xz(XzSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(leeL_cpp(Xz, W));
    return rcpp_result_gen;
END_RCPP
}
// leeL_perm_cpp
arma::cube leeL_perm_cpp(const arma::mat& Xz, const arma::sp_mat& W, const arma::umat& idx_mat);
RcppExport SEXP _FG2CLI_leeL_perm_cpp(SEXP XzSEXP, SEXP WSEXP, SEXP idx_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xz(XzSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type idx_mat(idx_matSEXP);
    rcpp_result_gen = Rcpp::wrap(leeL_perm_cpp(Xz, W, idx_mat));
    return rcpp_result_gen;
END_RCPP
}
// grad_betas_cpp
arma::mat grad_betas_cpp(const arma::mat& Xz, const arma::vec& cx, const arma::vec& cy);
RcppExport SEXP _FG2CLI_grad_betas_cpp(SEXP XzSEXP, SEXP cxSEXP, SEXP cySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xz(XzSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cx(cxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cy(cySEXP);
    rcpp_result_gen = Rcpp::wrap(grad_betas_cpp(Xz, cx, cy));
    return rcpp_result_gen;
END_RCPP
}
// leeL_perm_ge_cpp
arma::mat leeL_perm_ge_cpp(const arma::mat& Xz, const arma::sp_mat& W, const arma::umat& idx_mat, const arma::mat& L_ref);
RcppExport SEXP _FG2CLI_leeL_perm_ge_cpp(SEXP XzSEXP, SEXP WSEXP, SEXP idx_matSEXP, SEXP L_refSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xz(XzSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type idx_mat(idx_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L_ref(L_refSEXP);
    rcpp_result_gen = Rcpp::wrap(leeL_perm_ge_cpp(Xz, W, idx_mat, L_ref));
    return rcpp_result_gen;
END_RCPP
}
// leeL_minusR_perm_ge_cpp
arma::mat leeL_minusR_perm_ge_cpp(const arma::mat& Xz, const arma::sp_mat& W, const arma::umat& idx_mat, const arma::mat& Delta_ref);
RcppExport SEXP _FG2CLI_leeL_minusR_perm_ge_cpp(SEXP XzSEXP, SEXP WSEXP, SEXP idx_matSEXP, SEXP Delta_refSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xz(XzSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type idx_mat(idx_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Delta_ref(Delta_refSEXP);
    rcpp_result_gen = Rcpp::wrap(leeL_minusR_perm_ge_cpp(Xz, W, idx_mat, Delta_ref));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FG2CLI_idelta_cpp", (DL_FUNC) &_FG2CLI_idelta_cpp, 1},
    {"_FG2CLI_leeL_cpp", (DL_FUNC) &_FG2CLI_leeL_cpp, 2},
    {"_FG2CLI_leeL_perm_cpp", (DL_FUNC) &_FG2CLI_leeL_perm_cpp, 3},
    {"_FG2CLI_grad_betas_cpp", (DL_FUNC) &_FG2CLI_grad_betas_cpp, 3},
    {"_FG2CLI_leeL_perm_ge_cpp", (DL_FUNC) &_FG2CLI_leeL_perm_ge_cpp, 4},
    {"_FG2CLI_leeL_minusR_perm_ge_cpp", (DL_FUNC) &_FG2CLI_leeL_minusR_perm_ge_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_FG2CLI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
