# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

idelta_cpp <- function(G) {
    .Call(`_FG2CLI_idelta_cpp`, G)
}

leeL_cpp <- function(Xz, W) {
    .Call(`_FG2CLI_leeL_cpp`, Xz, W)
}

leeL_perm_cpp <- function(Xz, W, idx_mat) {
    .Call(`_FG2CLI_leeL_perm_cpp`, Xz, W, idx_mat)
}

grad_betas_cpp <- function(Xz, cx, cy) {
    .Call(`_FG2CLI_grad_betas_cpp`, Xz, cx, cy)
}

leeL_perm_ge_cpp <- function(Xz, W, idx_mat, L_ref) {
    .Call(`_FG2CLI_leeL_perm_ge_cpp`, Xz, W, idx_mat, L_ref)
}

leeL_minusR_perm_ge_cpp <- function(Xz, W, idx_mat, Delta_ref) {
    .Call(`_FG2CLI_leeL_minusR_perm_ge_cpp`, Xz, W, idx_mat, Delta_ref)
}

